### ISSUE TITLE
Show all Block Labels, When Unchecked, Hides Labels for Effect Blocks

### ISSUE THREAD

**Issue by skybaks** [XertroV/tm-editor-ui-toolbox#3]
The effect blocks normally have labels enabled by the game so that you can easily tell them apart. However, when the setting is unchecked *every* label in the inventory is hidden regardless of whether it was shown by the plugin or the game.

**Comment by XertroV** [comment]
Yeah, this is known (I think I have a warning in the settings about it). It might naturally recover itself if the setting to 'false' is skipped. The mobils are created and destroyed as you browse the inventory, so it's not straight forward to cache initial values.

**Comment by skybaks** [comment]
My point was that simply by having the plugin installed, these labels are hidden in my editor's inventory. Why not have a setting that would skip it altogether and then the other features of the plugin would be available without this downside?

**Comment by XertroV** [comment]
Fixed in next version. It shouldn't override the game default now (which is the implied by the setting and is the intention)

**Comment by skybaks** [comment]
Thanks!
